<a href="https://colab.research.google.com/github/arendon1/Universidad_2510B04G1_Analitica/blob/main/IntroNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Numerical Python

## ¿Qué es?
Librería fundamental para computación científica en Python. Proporciona soporte para arrays multidimensionales y operaciones matemáticas de alto rendimiento.

## ¿Para qué sirve?
- Operaciones vectorizadas (sin bucles explícitos)
- Álgebra lineal y cálculo numérico
- Generación de números aleatorios
- Procesamiento eficiente de grandes volúmenes de datos
- Base para otras librerías (pandas, scikit-learn, matplotlib)

In [26]:
import numpy as np #Importacio de numpy para su uso
from rich import print
from rich.console import Console
from rich.table import Table

console = Console()

In [27]:
matriz_A =  np.array([1,2,3,4,5])

print(matriz_A) # Ver matriz
print(type(matriz_A)) # Ver tipo de dato esta en variable.

matriz_B = np.array([.5,.8,.4, 1.5])

print(matriz_B)

[1 2 3 4 5]

<class 'numpy.ndarray'>

[0.5 0.8 0.4 1.5]

In [28]:
## Comparativa con listas
list_A = [1,2,3,4,5]
print(list_A)
print(type(list_A))

### Lista con tipos de datos mezclados.
list_B = ["A","B",1,2]
print(list_B)


[1, 2, 3, 4, 5]

<class 'list'>

['A', 'B', 1, 2]

> Es importante no confundir las listas nativos de python con los arrays propios de numpy como tal para evitar

In [29]:
MATRIZ_A = np.array([
    [1,2,3],
])
MATRIZ_B = np.array([
    [4,5,6],
])

print(MATRIZ_A, "\n")
print(MATRIZ_B, "\n")

print(MATRIZ_A + MATRIZ_B,"\n")

[[1 2 3]]

[[4 5 6]]

[[5 7 9]]

In [30]:
### Creando matrices multidiemnsionales

MATRIZ_2D = np.array([
    [1,2,3]
    ,[4,5,6]
])
print(MATRIZ_2D)
MATRIZ_2D.ndim

[[1 2 3]
 [4 5 6]]

2

In [31]:
###  Creando matrices aleatorias con NumPy

MATRIZ_RANDOM = np.arange(9).reshape(3,3)

print(MATRIZ_RANDOM,"\n")
print(MATRIZ_RANDOM.size)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

9

In [32]:
### Creando matrices con limites definidos, a traves de parametros

MATRIZ_DEF = np.linspace(0,100,25)
# TODO Investigar mas sobre linspace()
print(MATRIZ_DEF,"\n")
print(MATRIZ_DEF.shape,"\n")
print(MATRIZ_DEF.size,"\n")


[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]

(25,)

25

In [35]:
# MATRICES DE 3 O MAS DIMENSIONES
MATRIZ_3D = np.arange(24).reshape(2,3,4) # Crea dos matrices 3X4

print(MATRIZ_3D,"\n")
print(MATRIZ_3D.ndim,"\n")
print(MATRIZ_3D.size,"\n")


MATRIZ_GRANDE = np.arange(27).reshape(3,3,3) # Crea 3 matrices 3X3 con numeros del 1-27
print(MATRIZ_GRANDE,"\n")
print(MATRIZ_GRANDE.ndim,"\n")
print(MATRIZ_GRANDE.size,"\n")

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

3

24

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

3

27

In [36]:
## Trabajando con indices de posicion dentro de la matriz
MATRIZ_A = np.arange(24).reshape(4,6)
print(MATRIZ_A,"\n")
print(MATRIZ_A[3,4])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

22

In [42]:
## Oganizando una matriz de manera ascendente

MATRIZ_RANDOM = np.array([12,342,35,345,34,6,456,456,546,43])
print(MATRIZ_RANDOM,"\n")
print(np.sort(MATRIZ_RANDOM),"\n")

[ 12 342  35 345  34   6 456 456 546  43]

[  6  12  34  35  43 342 345 456 456 546]